In [1]:
import numpy as np
import pandas as pd

import os

import datetime, warnings
warnings.filterwarnings("ignore")

import kagglehub

In [2]:
# Download latest version
path = kagglehub.dataset_download("hrishitpatil/flight-data-2024")

print("Path to dataset files:", path)

data_path = os.path.join( path, 'flight_data_2024.csv')

Path to dataset files: C:\Users\USER\.cache\kagglehub\datasets\hrishitpatil\flight-data-2024\versions\2

In [3]:
#data_path = './flight_data_2024.csv'

In [4]:
def ver_df(path, columna_buscar):
    df = pd.read_csv(path, encoding='utf-8', sep=',')

    print(f"cantidad de muestras: {df.shape[0]}")
    print(f"cantidad de columnas: {df.shape[1]}")
    #print(f'Demo del data frame: \n{df.head(15)}')
    print(f'info del data frame: \n{df.info()}')
    print(f'descripción del data frame: \n{df.describe()}')
    print(f'columnas con valores nulos: \n{df.isna().sum()}')
    print(f'cantidad de valores del data frame: \n{df[columna_buscar].value_counts()}')
    print(f"cantidad de muestras validas: \n {df.shape[0]-df[columna_buscar].isna().sum()}")
    return df

In [5]:
df = ver_df(data_path, 'arr_delay')

cantidad de muestras: 7079081
cantidad de columnas: 35
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7079081 entries, 0 to 7079080
Data columns (total 35 columns):
 #   Column               Dtype
---  ------               -----
 0   year                 int64
 1   month                int64
 2   day_of_month         int64
 3   day_of_week          int64
 4   fl_date              object
 5   op_unique_carrier    object
 6   op_carrier_fl_num    float64
 7   origin               object
 8   origin_city_name     object
 9   origin_state_nm      object
 10  dest                 object
 11  dest_city_name       object
 12  dest_state_nm        object
 13  crs_dep_time         int64
 14  dep_time             float64
 15  dep_delay            float64
 16  taxi_out             float64
 17  wheels_off           float64
 18  wheels_on            float64
 19  taxi_in              float64
 20  crs_arr_time         int64
 21  arr_time             float64
 22  arr_delay            float64
 23  cancelled            int64
 24  cancellation_code    object
 25  diverted             int64
 26  crs_elapsed_time     float64
 27  actual_elapsed_time  float64
 28  air_time             float64
 29  distance             float64
 30  carrier_delay        int64
 31  weather_delay        int64
 32  nas_delay            int64
 33  security_delay       int64
 34  late_aircraft_delay  int64
dtypes: float64(13), int64(13), object(9)
memory usage: 1.8+ GB
info del data frame:
None
descripción del data frame:
            year         month  day_of_month   day_of_week  op_carrier_fl_num  \
count  7079081.0  7.079081e+06  7.079081e+06  7.079081e+06       7.079080e+06
mean      2024.0  6.584868e+00  1.578445e+01  3.981945e+00       2.504623e+03
std          0.0  3.396806e+00  8.786433e+00  2.012279e+00       1.652253e+03
min       2024.0  1.000000e+00  1.000000e+00  1.000000e+00       1.000000e+00
25%       2024.0  4.000000e+00  8.000000e+00  2.000000e+00       1.151000e+03
50%       2024.0  7.000000e+00  1.600000e+01  4.000000e+00       2.227000e+03
75%       2024.0  1.000000e+01  2.300000e+01  6.000000e+00       3.717000e+03
max       2024.0  1.200000e+01  3.100000e+01  7.000000e+00       8.819000e+03

       crs_dep_time      dep_time     dep_delay      taxi_out    wheels_off  \
count  7.079081e+06  6.986422e+06  6.986111e+06  6.983347e+06  6.983347e+06
mean   1.327300e+03  1.330765e+03  1.267708e+01  1.790445e+01  1.353542e+03
std    4.930306e+02  5.094779e+02  5.605997e+01  9.677410e+00  5.120475e+02
min    1.000000e+00  1.000000e+00 -9.600000e+01  1.000000e+00  1.000000e+00
25%    9.050000e+02  9.080000e+02 -6.000000e+00  1.200000e+01  9.240000e+02
50%    1.320000e+03  1.325000e+03 -2.000000e+00  1.500000e+01  1.338000e+03
75%    1.736000e+03  1.746000e+03  9.000000e+00  2.100000e+01  1.801000e+03
max    2.400000e+03  2.400000e+03  3.777000e+03  2.140000e+02  2.400000e+03

       ...      diverted  crs_elapsed_time  actual_elapsed_time      air_time  \
count  ...  7.079081e+06      7.079080e+06         6.965267e+06  6.965267e+06
mean   ...  2.471931e-03      1.467665e+02         1.412151e+02  1.149997e+02
std    ...  4.965703e-02      7.238692e+01         7.230781e+01  7.036955e+01
min    ...  0.000000e+00     -1.600000e+02         1.500000e+01  5.000000e+00
25%    ...  0.000000e+00      9.300000e+01         8.800000e+01  6.300000e+01
50%    ...  0.000000e+00      1.300000e+02         1.250000e+02  9.800000e+01
75%    ...  0.000000e+00      1.770000e+02         1.720000e+02  1.450000e+02
max    ...  1.000000e+00      1.326000e+03         7.920000e+02  7.230000e+02

           distance  carrier_delay  weather_delay     nas_delay  \
count  7.079081e+06   7.079081e+06   7.079081e+06  7.079081e+06
mean   8.339062e+02   5.060440e+00   8.752369e-01  2.771828e+00
std    5.962536e+02   3.572703e+01   1.542974e+01  1.546485e+01
min    1.100000e+01   0.000000e+00   0.000000e+00  0.000000e+00
25%    3.990000e+02   0.000000e+00   0.000000e+00  0.000000e+00
50%    6.800000e+02   0.000000e+00   0.000000e+00  0.000000e+00
75%    1.069000e+03   0.000000e+00   0.000000e+00  0.000000e+00
max    5.095000e+03   3.689000e+03   1.804000e+03  2.700000e+03

       security_delay  late_aircraft_delay
count    7.079081e+06         7.079081e+06
mean     2.541686e-02         5.929302e+00
std      1.422602e+00         3.106135e+01
min      0.000000e+00         0.000000e+00
25%      0.000000e+00         0.000000e+00
50%      0.000000e+00         0.000000e+00
75%      0.000000e+00         0.000000e+00
max      1.164000e+03         2.690000e+03

[8 rows x 26 columns]
columnas con valores nulos:
year                         0
month                        0
day_of_month                 0
day_of_week                  0
fl_date                      0
op_unique_carrier            0
op_carrier_fl_num            1
origin                       0
origin_city_name             0
origin_state_nm              0
dest                         0
dest_city_name               0
dest_state_nm                0
crs_dep_time                 0
dep_time                 92659
dep_delay                92970
taxi_out                 95734
wheels_off               95734
wheels_on                97856
taxi_in                  97856
crs_arr_time                 0
arr_time                 97854
arr_delay               113814
cancelled                    0
cancellation_code      6982766
diverted                     0
crs_elapsed_time             1
actual_elapsed_time     113814
air_time                113814
distance                     0
carrier_delay                0
weather_delay                0
nas_delay                    0
security_delay               0
late_aircraft_delay          0
dtype: int64
cantidad de valores del data frame:
arr_delay
-12.0      195000
-11.0      194843
-10.0      193190
-13.0      192226
-9.0       189211
            ...
 1397.0         1
 1888.0         1
 2901.0         1
 1252.0         1
 1884.0         1
Name: count, Length: 1887, dtype: int64
cantidad de muestras validas:
 6965267

In [6]:
df.sample(10)

,year,month,day_of_month,day_of_week,fl_date,op_unique_carrier,op_carrier_fl_num,origin,origin_city_name,origin_state_nm,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
109336,2024,1,7,7,2024-01-07,AA,1880.0,DFW,"Dallas/Fort Worth, TX",Texas,...,0,181.0,173.0,152.0,1055.0,0,0,0,0,0
6751221,2024,12,14,6,2024-12-14,WN,3044.0,MCO,"Orlando, FL",Florida,...,0,135.0,119.0,98.0,759.0,0,0,0,0,0
4068975,2024,7,30,2,2024-07-30,UA,1537.0,DEN,"Denver, CO",Colorado,...,0,89.0,82.0,65.0,391.0,0,0,0,0,0
3740214,2024,7,14,7,2024-07-14,WN,2949.0,OAK,"Oakland, CA",California,...,0,80.0,75.0,60.0,445.0,0,0,0,0,0
6876760,2024,12,21,6,2024-12-21,DL,3047.0,MYR,"Myrtle Beach, SC",South Carolina,...,0,81.0,78.0,60.0,317.0,0,0,0,0,0
3617659,2024,7,8,1,2024-07-08,WN,4509.0,SAN,"San Diego, CA",California,...,0,80.0,75.0,51.0,304.0,0,0,0,0,0
4153506,2024,8,3,6,2024-08-03,WN,11.0,HOU,"Houston, TX",Texas,...,0,55.0,45.0,33.0,187.0,0,0,0,0,0
2186303,2024,4,28,7,2024-04-28,DL,1089.0,RSW,"Fort Myers, FL",Florida,...,0,108.0,96.0,75.0,515.0,0,0,0,0,0
3529827,2024,7,4,4,2024-07-04,MQ,3557.0,MIA,"Miami, FL",Florida,...,0,56.0,45.0,31.0,126.0,0,0,0,0,0
4149510,2024,8,3,6,2024-08-03,OO,3342.0,SAN,"San Diego, CA",California,...,0,75.0,78.0,49.0,314.0,0,0,0,0,0

#***Limpieza del data frame***

#*Limpiado NA*

In [7]:
columnas_con_nulos = ['op_carrier_fl_num', 'dep_time', 'dep_delay', 'taxi_out', 'wheels_off', 'wheels_on', 'taxi_in', 'arr_time', 'arr_delay', 'actual_elapsed_time','actual_elapsed_time', 'air_time']

df.dropna(subset=columnas_con_nulos, inplace=True)

total_filas = len(df)

print(total_filas)

6965266

In [8]:
df.sample(5)

,year,month,day_of_month,day_of_week,fl_date,op_unique_carrier,op_carrier_fl_num,origin,origin_city_name,origin_state_nm,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
4314328,2024,8,11,7,2024-08-11,UA,1770.0,EWR,"Newark, NJ",New Jersey,...,0,337.0,337.0,295.0,2454.0,0,0,0,0,0
1577801,2024,3,27,3,2024-03-27,WN,3174.0,MIA,"Miami, FL",Florida,...,0,200.0,178.0,152.0,1182.0,1,0,0,0,95
242313,2024,1,14,7,2024-01-14,OO,5621.0,RNO,"Reno, NV",Nevada,...,0,98.0,98.0,68.0,391.0,0,0,0,0,0
3147880,2024,6,15,6,2024-06-15,UA,1961.0,LAS,"Las Vegas, NV",Nevada,...,0,277.0,273.0,248.0,2065.0,25,0,0,0,0
6099043,2024,11,10,7,2024-11-10,YX,4359.0,JFK,"New York, NY",New York,...,0,93.0,88.0,53.0,290.0,0,0,0,0,0

In [9]:
#df.drop_duplicates(inplace=True)

In [10]:
columnas = df.columns
print(columnas)

Index(['year', 'month', 'day_of_month', 'day_of_week', 'fl_date',
       'op_unique_carrier', 'op_carrier_fl_num', 'origin', 'origin_city_name',
       'origin_state_nm', 'dest', 'dest_city_name', 'dest_state_nm',
       'crs_dep_time', 'dep_time', 'dep_delay', 'taxi_out', 'wheels_off',
       'wheels_on', 'taxi_in', 'crs_arr_time', 'arr_time', 'arr_delay',
       'cancelled', 'cancellation_code', 'diverted', 'crs_elapsed_time',
       'actual_elapsed_time', 'air_time', 'distance', 'carrier_delay',
       'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay'],
      dtype='object')

In [11]:
df.head(15)

,year,month,day_of_month,day_of_week,fl_date,op_unique_carrier,op_carrier_fl_num,origin,origin_city_name,origin_state_nm,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2024,1,1,1,2024-01-01,9E,4814.0,JFK,"New York, NY",New York,...,0,136.0,122.0,84.0,509.0,0,0,0,0,0
1,2024,1,1,1,2024-01-01,9E,4815.0,MSP,"Minneapolis, MN",Minnesota,...,0,130.0,114.0,88.0,622.0,0,0,0,0,0
2,2024,1,1,1,2024-01-01,9E,4817.0,JFK,"New York, NY",New York,...,0,106.0,90.0,61.0,288.0,0,0,0,0,0
3,2024,1,1,1,2024-01-01,9E,4817.0,RIC,"Richmond, VA",Virginia,...,0,111.0,76.0,51.0,288.0,0,0,0,0,0
4,2024,1,1,1,2024-01-01,9E,4818.0,DTW,"Detroit, MI",Michigan,...,0,79.0,70.0,45.0,237.0,0,0,0,0,0
5,2024,1,1,1,2024-01-01,9E,4822.0,JAX,"Jacksonville, FL",Florida,...,0,137.0,120.0,102.0,833.0,0,0,0,0,0
6,2024,1,1,1,2024-01-01,9E,4822.0,LGA,"New York, NY",New York,...,0,169.0,164.0,125.0,833.0,0,0,0,0,0
7,2024,1,1,1,2024-01-01,9E,4823.0,CHS,"Charleston, SC",South Carolina,...,0,118.0,99.0,86.0,641.0,0,0,0,0,0
8,2024,1,1,1,2024-01-01,9E,4823.0,LGA,"New York, NY",New York,...,0,149.0,123.0,101.0,641.0,0,0,0,0,0
9,2024,1,1,1,2024-01-01,9E,4828.0,ITH,"Ithaca/Cortland, NY",New York,...,0,79.0,67.0,43.0,189.0,0,0,0,0,0
10,2024,1,1,1,2024-01-01,9E,4828.0,JFK,"New York, NY",New York,...,0,71.0,57.0,41.0,189.0,0,0,0,0,0
11,2024,1,1,1,2024-01-01,9E,4830.0,ITH,"Ithaca/Cortland, NY",New York,...,0,88.0,86.0,43.0,189.0,0,0,0,0,0
12,2024,1,1,1,2024-01-01,9E,4836.0,CLE,"Cleveland, OH",Ohio,...,0,137.0,116.0,87.0,622.0,0,0,0,0,0
13,2024,1,1,1,2024-01-01,9E,4845.0,GRR,"Grand Rapids, MI",Michigan,...,0,62.0,68.0,30.0,120.0,0,0,0,0,0
14,2024,1,1,1,2024-01-01,9E,4851.0,CMH,"Columbus, OH",Ohio,...,0,63.0,51.0,34.0,155.0,0,0,0,0,0

#*Convertir de millas a km el campo dist*

In [12]:
df['distancia_km'] = df['distance'] * 1.60934

In [13]:
df.head(15)

,year,month,day_of_month,day_of_week,fl_date,op_unique_carrier,op_carrier_fl_num,origin,origin_city_name,origin_state_nm,...,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,distancia_km
0,2024,1,1,1,2024-01-01,9E,4814.0,JFK,"New York, NY",New York,...,136.0,122.0,84.0,509.0,0,0,0,0,0,819.15406
1,2024,1,1,1,2024-01-01,9E,4815.0,MSP,"Minneapolis, MN",Minnesota,...,130.0,114.0,88.0,622.0,0,0,0,0,0,1001.00948
2,2024,1,1,1,2024-01-01,9E,4817.0,JFK,"New York, NY",New York,...,106.0,90.0,61.0,288.0,0,0,0,0,0,463.48992
3,2024,1,1,1,2024-01-01,9E,4817.0,RIC,"Richmond, VA",Virginia,...,111.0,76.0,51.0,288.0,0,0,0,0,0,463.48992
4,2024,1,1,1,2024-01-01,9E,4818.0,DTW,"Detroit, MI",Michigan,...,79.0,70.0,45.0,237.0,0,0,0,0,0,381.41358
5,2024,1,1,1,2024-01-01,9E,4822.0,JAX,"Jacksonville, FL",Florida,...,137.0,120.0,102.0,833.0,0,0,0,0,0,1340.58022
6,2024,1,1,1,2024-01-01,9E,4822.0,LGA,"New York, NY",New York,...,169.0,164.0,125.0,833.0,0,0,0,0,0,1340.58022
7,2024,1,1,1,2024-01-01,9E,4823.0,CHS,"Charleston, SC",South Carolina,...,118.0,99.0,86.0,641.0,0,0,0,0,0,1031.58694
8,2024,1,1,1,2024-01-01,9E,4823.0,LGA,"New York, NY",New York,...,149.0,123.0,101.0,641.0,0,0,0,0,0,1031.58694
9,2024,1,1,1,2024-01-01,9E,4828.0,ITH,"Ithaca/Cortland, NY",New York,...,79.0,67.0,43.0,189.0,0,0,0,0,0,304.16526
10,2024,1,1,1,2024-01-01,9E,4828.0,JFK,"New York, NY",New York,...,71.0,57.0,41.0,189.0,0,0,0,0,0,304.16526
11,2024,1,1,1,2024-01-01,9E,4830.0,ITH,"Ithaca/Cortland, NY",New York,...,88.0,86.0,43.0,189.0,0,0,0,0,0,304.16526
12,2024,1,1,1,2024-01-01,9E,4836.0,CLE,"Cleveland, OH",Ohio,...,137.0,116.0,87.0,622.0,0,0,0,0,0,1001.00948
13,2024,1,1,1,2024-01-01,9E,4845.0,GRR,"Grand Rapids, MI",Michigan,...,62.0,68.0,30.0,120.0,0,0,0,0,0,193.12080
14,2024,1,1,1,2024-01-01,9E,4851.0,CMH,"Columbus, OH",Ohio,...,63.0,51.0,34.0,155.0,0,0,0,0,0,249.44770

In [14]:
aerolineas = {'9E': 'Endeavor Air', 'AA': 'American Airlines', 'AS': 'Alaska Airlines', 'B6': 'JetBlue Airways', 'DL': 'Delta Air Lines', 'F9': 'Frontier Airlines', 'G4': 'Allegiant Air', 'HA': 'Hawaiian Airlines', 'MQ': 'Envoy Air', 'NK': 'Spirit Airlines', 'OH': 'PSA Airlines', 'OO': 'SkyWest Airlines', 'UA': 'United Airlines', 'WN': 'Southwest Airlines', 'YX': 'Republic Airways'}

In [15]:
df['retraso'] = np.where(df['arr_delay']>0, 1, 0)

In [16]:
df.sample(15)

,year,month,day_of_month,day_of_week,fl_date,op_unique_carrier,op_carrier_fl_num,origin,origin_city_name,origin_state_nm,...,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,distancia_km,retraso
6749773,2024,12,14,6,2024-12-14,WN,1200.0,SJC,"San Jose, CA",California,...,140.0,117.0,948.0,0,0,0,0,0,1525.65432,0
2673077,2024,5,23,4,2024-05-23,AA,1905.0,DFW,"Dallas/Fort Worth, TX",Texas,...,115.0,92.0,685.0,37,0,0,0,13,1102.39790,1
3164222,2024,6,16,7,2024-06-16,NK,3125.0,DFW,"Dallas/Fort Worth, TX",Texas,...,197.0,155.0,1119.0,0,0,0,0,0,1800.85146,1
4657049,2024,8,29,4,2024-08-29,9E,5046.0,LGA,"New York, NY",New York,...,125.0,81.0,544.0,0,0,0,0,0,875.48096,0
7071792,2024,12,31,2,2024-12-31,OO,3995.0,ABQ,"Albuquerque, NM",New Mexico,...,120.0,88.0,493.0,0,0,0,0,0,793.40462,0
4360534,2024,8,13,2,2024-08-13,YX,4412.0,ILM,"Wilmington, NC",North Carolina,...,68.0,49.0,319.0,0,0,0,0,0,513.37946,0
5500684,2024,10,11,5,2024-10-11,B6,1565.0,BOS,"Boston, MA",Massachusetts,...,253.0,224.0,1764.0,0,0,0,0,0,2838.87576,0
4370407,2024,8,14,3,2024-08-14,NK,1142.0,FLL,"Fort Lauderdale, FL",Florida,...,261.0,240.0,1972.0,0,0,0,0,0,3173.61848,0
3135308,2024,6,15,6,2024-06-15,AA,1350.0,JAX,"Jacksonville, FL",Florida,...,149.0,129.0,864.0,0,0,0,0,0,1390.46976,0
2581435,2024,5,18,6,2024-05-18,F9,1338.0,PIT,"Pittsburgh, PA",Pennsylvania,...,138.0,117.0,328.0,0,0,49,0,0,527.86352,1
5238006,2024,9,27,5,2024-09-27,YX,4361.0,DCA,"Washington, DC",Virginia,...,93.0,68.0,323.0,0,0,0,0,20,519.81682,1
6454528,2024,11,29,5,2024-11-29,DL,1221.0,MKE,"Milwaukee, WI",Wisconsin,...,149.0,91.0,669.0,0,0,20,0,0,1076.64846,1
2237387,2024,4,30,2,2024-04-30,WN,295.0,PBI,"West Palm Beach/Palm Beach, FL",Florida,...,101.0,79.0,545.0,0,0,0,0,0,877.09030,0
6477027,2024,11,30,6,2024-11-30,MQ,3392.0,DFW,"Dallas/Fort Worth, TX",Texas,...,61.0,42.0,293.0,23,0,0,0,43,471.53662,1
2620812,2024,5,20,1,2024-05-20,G4,1861.0,PGD,"Punta Gorda, FL",Florida,...,100.0,79.0,588.0,0,0,0,0,0,946.29192,0

In [17]:
#columnas_basura = ['cancellation_code', 'distance', 'fl_date', 'cancelled', 'arr_delay']
"""nuevos_nombres_columnas = {'op_unique_carrier':'codigo_unico_aerolinea',
                              'dest':'codigo_destino',
                              'dep_time':'hora_salida',
                              'year':'año',
                              'month':'mes',
                              'day_of_month':'dia_mes',
                              'origin':'codigo_origen',
                              }
"""
#df.drop(columns=columnas_basura, inplace=True)

"nuevos_nombres_columnas = {'op_unique_carrier':'codigo_unico_aerolinea',\n                              'dest':'codigo_destino',\n                              'dep_time':'hora_salida',\n                              'year':'año',\n                              'month':'mes',\n                              'day_of_month':'dia_mes',\n                              'origin':'codigo_origen',\n                              }\n"

##**Exploración**

In [18]:
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

In [ ]:
data = df['retraso'].groupby(df['op_unique_carrier']).value_counts()
data

op_unique_carrier  retraso
9E                 0          144070
                   1           51002
AA                 0          561389
                   1          404727
AS                 0          140780
                   1           99543
B6                 0          144132
                   1           91551
DL                 0          682270
                   1          315576
F9                 0          114601
                   1           88880
G4                 0           74877
                   1           40005
HA                 0           44286
                   1           33347
MQ                 0          173870
                   1          101447
NK                 0          159000
                   1           96633
OH                 0          141158
                   1           82515
OO                 0          485665
                   1          248221
UA                 0          490577
                   1          255241
WN                 0          867079
                   1          537518
YX                 0          219504
                   1           75802
Name: count, dtype: int64

In [ ]:
plt.figure(figsize=(12, 6))
sns.barplot(x=data.index.get_level_values(0), y=data.values, hue=data.index.get_level_values(1))
plt.xlabel('Código de aerolínea')
plt.ylabel('Cantidad de vuelos')

In [ ]:
data = df['retraso'].groupby(df['origin']).value_counts()
data

In [ ]:
top10_origen = data.nlargest(10)
top10_origen

In [ ]:
data = df['retraso'].value_counts()
plt.figure(figsize=(10, 6))
plt.pie(data, labels=data.index, autopct='%1.1f%%', startangle=90)
plt.title('Distribución de vuelos retrasados')
plt.show()

In [ ]:
plt.figure(figsize=(12, 6))
sns.barplot(x=top10_origen.index.get_level_values(0), y=top10_origen.values, hue=top10_origen.index.get_level_values(1))
plt.xlabel('Código de aerolínea')
plt.ylabel('Cantidad de vuelos')

In [ ]:
y = df['retraso']
X = df.drop(['retraso'], axis=1)

In [ ]:
corr_matrix = df.corr(numeric_only=True)
plt.figure(figsize=(18, 14))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Matriz de correlación')
plt.show()

#**Preproceso**

In [ ]:
from sklearn.compose import make_column_selector as selector

In [ ]:
cat_selector = selector(dtype_include=['object', 'category'])
variables_categoricas = cat_selector(df)

In [ ]:
print(variables_categoricas)

['fl_date', 'op_unique_carrier', 'origin', 'origin_city_name', 'origin_state_nm', 'dest', 'dest_city_name', 'dest_state_nm', 'cancellation_code']

In [ ]:
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
one_hot = make_column_transformer(
    (OneHotEncoder(drop="if_binary", handle_unknown="ignore"), variables_categoricas),
    remainder="passthrough",
    sparse_threshold=0
)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, roc_auc_score,confusion_matrix, ConfusionMatrixDisplay, r2_score

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=200)

NameError: name 'X' is not defined

In [ ]:
model_arbol = Pipeline(steps=[
    ("preprocessor", one_hot),
    ("classifier", RandomForestClassifier(random_state=200, class_weight="balanced", max_depth=5))
])

In [ ]:
model_arbol.fit(X_train, y_train)

In [ ]:
y_pred = model_arbol.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

In [ ]:
matrix = confusion_matrix(y_test, y_pred)
print(matrix)
visualizacion = ConfusionMatrixDisplay(matrix, display_labels=['Retraso (NO)', 'Retraso (SI)'])
visualizacion.plot()